const PORTFOLIO_DATA = {
  featured: [
    {
      slug: "ankle-band",
      title: "Connected Ankle Band",
      eyebrow: "Wearable sensing · MVP",
      status: "Completed",
      period: "2025–2026",
      duration: "~4 months",
      context: "Independent",
      role: "Solo product engineer",
      summary: "A compact BLE wearable that combines motion and pressure sensing for high-rate movement capture in an ankle-worn form factor.",
      hero: "assets/projects/ankle-band/hero.jpg",
      gallery: ["assets/projects/ankle-band/hero.jpg", "assets/projects/ankle-band/board.png"],
      video: "assets/motion/ankle-band.mp4",
      tags: ["DA14531", "BMI270", "BLE", "Embedded C", "Wearables"],
      challenge: "Fit sensing, wireless communication and power management into a small wearable while keeping the data path responsive and the hardware manufacturable.",
      decisions: ["A DA14531 BLE module provides the low-power wireless core.", "BMI270 motion sensing is paired with an analog pressure channel.", "The firmware architecture is designed around 100 Hz acquisition and compact BLE packets."],
      architecture: ["Motion + pressure", "DA14531 acquisition", "BLE packet layer", "Companion interface"],
      engineering: ["Sensor bring-up and peripheral configuration", "Custom PCB design and compact placement", "BLE service and packet design", "Firmware timing and event-detection experiments"],
      testing: "Board bring-up, sensor communication and BLE data-flow checks were completed. Algorithm calibration remains an area for continued validation rather than a published performance claim.",
      result: "A complete working MVP spanning electronics, PCB, firmware and wireless data delivery.",
      links: [{label:"Firmware overview", url:"https://github.com/scientist444/AnkleBandV2-Firmware"}]
    },
    {
      slug: "aqi-monitor",
      title: "Multi-Sensor AQI Monitor",
      eyebrow: "Environmental sensing · MVP",
      status: "Completed",
      period: "2024–2025",
      duration: "~3 months",
      context: "RISETech",
      role: "Solo embedded engineer",
      summary: "An ESP32 air-quality platform that unifies particulate, gas, temperature and humidity sensing with local display and connected logging.",
      hero: "assets/projects/aqi-monitor/hero.png",
      gallery: ["assets/projects/aqi-monitor/hero.png"],
      video: "assets/motion/aqi-monitor.mp4",
      tags: ["ESP32", "Air quality", "Wi‑Fi", "Sensors", "PCB"],
      challenge: "Combine sensors with different electrical interfaces and power needs without turning the product into a wiring prototype.",
      decisions: ["ESP32 provides the central acquisition and Wi‑Fi path.", "The board supports gas, particulate, CO₂, temperature and humidity sensing.", "OLED feedback keeps the device useful without a network connection."],
      architecture: ["Gas + PM + climate sensors", "ESP32 acquisition", "OLED feedback", "Wi‑Fi database path"],
      engineering: ["Mixed-sensor interface planning", "Power-domain and connector layout", "Two-layer PCB implementation", "Local display and database integration"],
      testing: "The hardware was assembled and tested as a connected sensing MVP. Public material documents the supported sensor set and approximately nine-hour battery target.",
      result: "A consolidated, portable AQI node with local and remote visibility.",
      links: [{label:"Public PCB notes", url:"https://github.com/scientist444/pcb-portfolio"}]
    },
    {
      slug: "epic",
      title: "EPIC Biosignal Platform",
      eyebrow: "Biosignal acquisition · Product",
      status: "Completed",
      period: "2024–2025",
      duration: "~4 months",
      context: "RISETech",
      role: "Solo product engineer",
      summary: "A wearable-oriented electronics platform for synchronized physiological and motion sensing, designed from signal entry to a compact manufactured PCB.",
      hero: "assets/projects/epic/hero.png",
      gallery: ["assets/projects/epic/hero.png", "assets/projects/epic/prototype.jpg"],
      video: "assets/motion/epic.mp4",
      tags: ["Biosignals", "Analog front end", "ESP32", "IMU", "PCB"],
      challenge: "Route low-level physiological signals beside digital processing and wireless electronics while controlling noise, size and assembly risk.",
      decisions: ["Signal paths are separated by function and sensitivity.", "The controller and radio are kept in a compact central domain.", "Board views shown publicly are intentionally limited to protect implementation detail."],
      architecture: ["Physiological inputs", "Analog front end", "MCU + motion sensing", "Wired / wireless interface"],
      engineering: ["Mixed-signal partitioning", "Component selection and schematic ownership", "PCB placement, routing and DFM", "Prototype bring-up and iteration"],
      testing: "Power, controller and acquisition paths were brought up on manufactured hardware. Detailed signal-chain values remain private.",
      result: "A completed product-level embedded platform with a compact, fabrication-ready board.",
      links: []
    },
    {
      slug: "ergonomic-mouse",
      title: "Ergonomic BLE Mouse",
      eyebrow: "Assistive input · MVP",
      status: "Completed",
      period: "2024–2025",
      duration: "~3 months",
      context: "Product engineering",
      role: "Solo embedded engineer",
      summary: "A custom semicircular mouse controller with dual joystick inputs, buttons and an ESP32-S3 BLE HID implementation.",
      hero: "assets/projects/ergonomic-mouse/hero.jpg",
      gallery: ["assets/projects/ergonomic-mouse/hero.jpg", "assets/projects/ergonomic-mouse/prototype.jpg"],
      video: "assets/motion/ergonomic-mouse.mp4",
      tags: ["ESP32‑S3", "BLE HID", "Arduino", "Human interface", "PCB"],
      challenge: "Translate an unusual ergonomic input concept into reliable HID behavior inside a strict curved mechanical envelope.",
      decisions: ["Dual analog joysticks support pointer and scroll functions.", "ESP32-S3 handles BLE HID and wired development paths.", "The PCB outline follows the enclosure instead of forcing a rectangular board."],
      architecture: ["Joysticks + buttons", "Input filtering", "ESP32‑S3 HID", "BLE / USB host"],
      engineering: ["HID firmware and input mapping", "Mechanical-outline-aware PCB design", "Connector and programming access", "Manufacturing and assembled-board testing"],
      testing: "Firmware variants document joystick, click and scroll behavior. The two-layer board was manufactured and tested.",
      result: "A working ergonomic input MVP with custom electronics and BLE firmware.",
      links: [{label:"Public PCB notes", url:"https://github.com/scientist444/pcb-portfolio"}]
    },
    {
      slug: "embedded-microscope",
      title: "Embedded Microscope Controller",
      eyebrow: "Imaging hardware · MVP",
      status: "Completed",
      period: "2025–2026",
      duration: "~3 months",
      context: "Independent",
      role: "Solo hardware engineer",
      summary: "A purpose-built ESP32 control board that centralizes the power, USB and peripheral connections needed by a compact digital microscope system.",
      hero: "assets/projects/embedded-microscope/hero.png",
      gallery: ["assets/projects/embedded-microscope/hero.png", "assets/projects/embedded-microscope/board.png"],
      video: "assets/motion/embedded-microscope.mp4",
      tags: ["ESP32", "Imaging", "USB", "Power", "PCB"],
      challenge: "Replace loose development modules with one serviceable controller shaped around the microscope’s connectors and physical constraints.",
      decisions: ["A modular ESP32 core keeps firmware iteration practical.", "Power and external interfaces are grouped by function.", "Large mounting and connector clearances are treated as first-class constraints."],
      architecture: ["Imaging peripherals", "ESP32 controller", "Power + USB interfaces", "External controls"],
      engineering: ["System connector mapping", "Power-entry and regulation design", "Custom board outline and mounting", "3D clearance review"],
      testing: "The design progressed through schematic, layout and 3D mechanical inspection. Public views are limited to the controller overview.",
      result: "A complete controller-board MVP ready for system-level integration.",
      links: []
    },
    {
      slug: "pd-charger",
      title: "USB‑C PD Power Controller",
      eyebrow: "Power electronics · MVP",
      status: "Completed",
      period: "2025–2026",
      duration: "~3 months",
      context: "Independent",
      role: "Solo hardware engineer",
      summary: "A compact USB‑C Power Delivery board that negotiates an input profile and creates controlled rails for an embedded load.",
      hero: "assets/projects/pd-charger/hero.png",
      gallery: ["assets/projects/pd-charger/hero.png"],
      video: "assets/motion/pd-charger.mp4",
      tags: ["USB‑C PD", "DC/DC", "Power integrity", "ESP32", "PCB"],
      challenge: "Coordinate PD negotiation, high-current conversion and low-voltage control on a compact board without exposing sensitive implementation details.",
      decisions: ["USB-C is the single external power entry.", "Power conversion and logic domains are physically separated.", "Accessible test points and edge connectors support bring-up."],
      architecture: ["USB‑C PD input", "Negotiation + protection", "Buck conversion", "Embedded load rails"],
      engineering: ["Power-tree definition", "Protection and conversion selection", "High-current placement and routing", "3D/DFM review"],
      testing: "The completed design includes schematic, layout and 3D review. Exact component values and complete schematics are intentionally withheld.",
      result: "A compact, fabrication-ready power-control MVP.",
      links: []
    },
    {
      slug: "smart-stethoscope",
      title: "Smart Stethoscope",
      eyebrow: "Medical sensing · MVP",
      status: "In progress",
      period: "2026–Present",
      duration: "Active development",
      context: "RISETech",
      role: "Solo product engineer",
      summary: "A low-noise, multi-sensor auscultation platform combining acoustic and contact vibration sensing with a BLE data path.",
      hero: "assets/projects/smart-stethoscope/hero.png",
      gallery: ["assets/projects/smart-stethoscope/hero.png", "assets/projects/smart-stethoscope/board.png"],
      video: "assets/motion/smart-stethoscope.mp4",
      tags: ["MEMS microphone", "PVDF", "Low-noise AFE", "BLE", "Medical device"],
      challenge: "Preserve weak body sounds through the analog chain while integrating sensing, digitization, wireless communication and battery operation.",
      decisions: ["Dual analog MEMS channels capture acoustic information.", "A PVDF channel adds direct diaphragm-vibration sensing.", "The analog front end is separated from the BLE/digital domain."],
      architecture: ["MEMS + PVDF sensors", "Low-noise analog front end", "Multi-channel ADC", "BLE companion app"],
      engineering: ["Sensor and analog-front-end selection", "Mixed-signal PCB partitioning", "Battery and charging architecture", "Contact-quality and monitoring concepts"],
      testing: "The first hardware design is complete and the project is now in active bring-up and signal-quality validation.",
      result: "An active MVP with the complete electronics architecture and first PCB implementation in place.",
      links: []
    },
    {
      slug: "vehicle-profiling",
      title: "Edge Vehicle Profiling Node",
      eyebrow: "Sensor fusion · MVP",
      status: "Completed",
      period: "2025–2026",
      duration: "~4 months",
      context: "Independent research",
      role: "Solo embedded engineer",
      summary: "A rugged multi-sensor node that captures complementary roadside signatures and provides a structured path to desktop analysis.",
      hero: "assets/projects/vehicle-profiling/hero.png",
      gallery: ["assets/projects/vehicle-profiling/hero.png", "assets/projects/vehicle-profiling/board.png"],
      video: "assets/motion/vehicle-profiling.mp4",
      tags: ["STM32", "Sensor fusion", "Edge acquisition", "Python", "Enclosure"],
      challenge: "Collect time-aligned signals from very different sensors in a field-ready enclosure and keep the dataset useful for later analysis.",
      decisions: ["Seismic, magnetic, infrared and ranging signals provide complementary observations.", "An STM32-centered board handles deterministic acquisition.", "A Python plotting workflow supports dataset inspection and iteration."],
      architecture: ["Roadside sensor array", "Signal conditioning", "STM32 acquisition", "Storage / desktop analysis"],
      engineering: ["Multi-sensor interface design", "Custom PCB and protected connectors", "Enclosure integration", "Python dataset plotting workflow"],
      testing: "The assembled node and enclosure were exercised through staged captures. Public claims are limited to the completed acquisition workflow, not classifier accuracy.",
      result: "A complete field-oriented sensing MVP from hardware through analysis tooling.",
      links: [{label:"Python plotter", url:"https://github.com/scientist444/Ploter"}]
    }
  ],
  earlier: [
    {title:"EKKO Wearable System", meta:"RISETech · Product · Completed", summary:"Consolidated hardware and interface work for a connected wearable product.", tags:["Wearable", "Embedded", "Product lifecycle"], image:"images/ekko-device.jpg"},
    {title:"Avionics Automated Test Procedures", meta:"RIMS / NASTP Alpha · 2025", summary:"Python and LabVIEW test tooling for avionics LRUs, portable diagnostics and Ubuntu system-health monitoring.", tags:["Python", "LabVIEW", "Test engineering"], image:"images/python-gui-system-monitor.JPG"},
    {title:"GNU Radio SDR Pipeline", meta:"RIMS / NASTP Alpha · 2025", summary:"USRP X310 transmit/receive workflows and spectral analysis in GNU Radio Companion.", tags:["GNU Radio", "USRP X310", "RF"], image:"images/gnu-radio-usrp-x310.jpeg"},
    {title:"Competition Line-Following Robot", meta:"AirTech ’24 · 1st place", summary:"STM32 control board with five-channel IR sensing and dual motor drive, manufactured and tested.", tags:["STM32", "Robotics", "PCB"], image:"images/lfr-airtech24-winner.jpeg", link:"https://github.com/scientist444/pcb-portfolio"},
    {title:"Long-Range LoRa Link", meta:"Independent · Tested", summary:"ATmega328P and SX1278 point-to-point boards documented at distances up to 10 km.", tags:["LoRa", "ATmega328P", "RF"], image:"images/p2p-lora-device.jpeg", link:"https://github.com/scientist444/pcb-portfolio"}
  ]
};

if (typeof window !== "undefined") window.PORTFOLIO_DATA = PORTFOLIO_DATA;
